### ISSUE TITLE
Conflict with the patch (dk_mmenu.css) and the "front" position.

### ISSUE THREAD

**Issue by lionel-m** [dklemmt/contao_dk_mmenu#1]
Hi,

There is a conflict with the patch (dk_mmenu.css) and the "front" position.

We need to keep the value of 0 for [the margin](https://github.com/dklemmt/contao_dk_mmenu/blob/c32336367a19be6e70595cd01e5b39bf942f7f4d/system/modules/dk_mmenu/assets/css/mmenu-positioning.css#L101-L108).

A solution is to add : 

``` CSS
html.mm-front.mm-opening .mm-page
    {
        margin: 0 !important;
    }
```

in `dk_mmenu.css` or make a test and does not include the css file if the "front" position is used...
